### ISSUE TITLE
Realtime/Websocket API sometimes fails to return PONG?

### ISSUE THREAD

**Issue by bachya** [ambient-weather/api-docs#30]
Home Assistant users of the Ambient Weather integration are [reporting](https://github.com/ambient-weather/api-docs/issues/30) that the underlying library (`python-engineio`, as part of `aioambient`) sometimes returns `packet queue is empty, aborting` error messages.

Some [research](https://stackoverflow.com/a/66460290) on what this means:

>So packet queue is empty, aborting is a product of the underlying python-engineio package and is triggered when empty payloads are sent and I believe when the ongoing PING / PONG between server and client is missed on the server-side.
>
>As such, it looks like the main problem you're dealing with is the client is disconnecting because the server isn't able to PONG back to the client and the client eventually gives up and disconnects.

Not sure how to tie things together, but wanted to share in case there's something that needs tuning in the realtime API.

**Comment by yang3535** [comment]
Here's a related post from a python forum:  https://stackoverflow.com/questions/66441954/socketio-packet-queue-is-empty-aborting-error-when-sending-message-from-serve

**Comment by autumnwalker** [comment]
Seeing the same issue with my Ambient integration as well. Ambient - any updates?

**Comment by tankdeer** [comment]
Any updates? This is very much still an

**Comment by willp** [comment]
The test connection is still good 1 hour later, no disconnects and data looks perfect.
I'll stop my test client now.  I'd call it pretty solid!

**Comment by owise1** [comment]
Thanks @willp for testing this. I'm going to scale up this process to a few more nodes to make sure everything continues to be stable.

As far as production goes, because of our internal structure it was necessary to tease out the socket functionality to fix this issue. That means that `rt2.ambientweather.net` is going to become the production endpoint for the realtime api. The rest api will remain at `rt.ambientweather.net`.  I realize this adds some unwelcome complexity, but so it goes.   As soon as we can confirm everything's all good we'll update the documentation accordingly.

**Comment by bachya** [comment]
Thanks for your work, @owise1! For [`aioambient`](https://github.com/bachya/aioambient), I've been using `https://api.ambientweather.net` for both REST and websocket APIs; I assume that once you give the go-ahead from ^^^, I should switch ASAP?

**Comment by owise1** [comment]
@bachya We're still supporting `api.ambientweather.net` but it's probably better to switch your REST endpoint to `rt.ambientweather.net`. And then yeah, I'd say test out `rt2.ambientweather.net` for real time and if it seems better make the switch.
