### ISSUE TITLE
Limit=1 Bug

### ISSUE THREAD

**Issue by PapaRad** [ambient-weather/api-docs#54]
Setting limit=1 often causes the API to return an empty array [].  

Based on docs, seems like if endDate is not specified and limit=1 the most recent observation should always be returned.  Surprisingly, changing limit=2 does return the most recent record in many cases, and not the two most recent records.

I've replicated the bug with four different weather stations.

```
https://rt.ambientweather.net/v1/devices/macAddress?apiKey=&applicationKey=&endDate=&limit=1
// Returns []
```

```
https://rt.ambientweather.net/v1/devices/macAddress?apiKey=&applicationKey=&endDate=&limit=2
// Returns [{"dateutc":1729199280000,"windspeedmph":5.145,"windgustmph":17.2244,"hourlyrainin":0,"dailyrainin":0,"trustdevicetime":"1","winddir":181,"tempf":63.1,"humidity":28,"baromabsin":29.32,"baromrelin":30.2455,"feelsLike":63.1,"dewPoint":29.47,"lastRain":"2024-10-15T15:53:00.000Z","date":"2024-10-17T21:08:00.000Z"}]
```

**Comment by owise1** [comment]
if all you want is the most recent data the best endpoint to use is actually `/devices` because the devices returned will always contain the most recent data point.  (https://ambientweather.docs.apiary.io/#reference/0/devices/list-user's-devices) assuming your station reports every minute, you can hit this endpoint every minute for new data.  the historical data is only stored every 5 mins. that's what you get back from `/devices/macAddress`

as far as your limit issue, we aren't able to reproduce this issue.  if you still need help contact support@ambientweather.com with your specific account/stations and we can check it out. you can tell them to immediately escalate your issue to the dev team.
